# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NatsDiscover < Formula
  desc "CLI tool to discover NATS services using the nats-service framework"
  homepage "https://github.com/transactrx/nats-service"
  version "1.4.45"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/transactrx/nats-service/releases/download/v1.4.45/nats-discover_1.4.45_darwin_amd64.tar.gz"
      sha256 "92596a65c330f2c9df3602c0057f80089a18780f0cab271a25be2203668a7a43"

      def install
        bin.install "nats-discover"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/transactrx/nats-service/releases/download/v1.4.45/nats-discover_1.4.45_darwin_arm64.tar.gz"
      sha256 "0e312017bbb14ebfa648cfcae2332e541b9216000796d8648b88e2c7a7c27a40"

      def install
        bin.install "nats-discover"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/transactrx/nats-service/releases/download/v1.4.45/nats-discover_1.4.45_linux_amd64.tar.gz"
      sha256 "b7b65f9a823a3160d23e828e1803389d36ba4e8a246b4ce49ea88a7bbd295415"
      def install
        bin.install "nats-discover"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/transactrx/nats-service/releases/download/v1.4.45/nats-discover_1.4.45_linux_arm64.tar.gz"
      sha256 "2ba84d4dcc34de0b847f32bee15b871274d30a0659517fe1d7a40e282d507941"
      def install
        bin.install "nats-discover"
      end
    end
  end

  test do
    system "#{bin}/nats-discover", "--version"
  end
end
