# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NatsDiscover < Formula
  desc "CLI tool to discover NATS services using the nats-service framework"
  homepage "https://github.com/transactrx/nats-service"
  version "1.4.47"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/transactrx/nats-service/releases/download/v1.4.47/nats-discover_1.4.47_darwin_amd64.tar.gz"
      sha256 "2fb5526a6f92dc4799976aa43c3f09a2a0b2fcd47cfbc0c21d2b2fb3ce0b8bb8"

      define_method(:install) do
        bin.install "nats-discover"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/transactrx/nats-service/releases/download/v1.4.47/nats-discover_1.4.47_darwin_arm64.tar.gz"
      sha256 "df406eb31ee5c0b18dd0c9cc62679662c2a9078eb4885a5c695fb67e5ef2456e"

      define_method(:install) do
        bin.install "nats-discover"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/transactrx/nats-service/releases/download/v1.4.47/nats-discover_1.4.47_linux_amd64.tar.gz"
      sha256 "a5cf46f42ab36bcfa7eac80e9ab081c29d9ad7e11d95a22d59e81f66882504b9"
      define_method(:install) do
        bin.install "nats-discover"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/transactrx/nats-service/releases/download/v1.4.47/nats-discover_1.4.47_linux_arm64.tar.gz"
      sha256 "28284893200852f0b4d38249323454ea5398f2c02383540e936b3d6d6e5cac56"
      define_method(:install) do
        bin.install "nats-discover"
      end
    end
  end

  test do
    system "#{bin}/nats-discover", "--version"
  end
end
