# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NatsAgents < Formula
  desc "CLI to discover and drive NATS Agent Protocol agents and network tools"
  homepage "https://github.com/transactrx/nats-agent"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/transactrx/nats-agent/releases/download/v0.1.3/nats-agents_0.1.3_darwin_amd64.tar.gz"
      sha256 "6d222e64f3907e64bc2c6e591c356514207ac3f4697a343ea9a90abbfe3b3608"

      define_method(:install) do
        bin.install "nats-agents"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/transactrx/nats-agent/releases/download/v0.1.3/nats-agents_0.1.3_darwin_arm64.tar.gz"
      sha256 "33f77ac2b6d7c94192fb2360be0159d53825db2bd363d9e0b5f72a8f9cfd45fd"

      define_method(:install) do
        bin.install "nats-agents"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/transactrx/nats-agent/releases/download/v0.1.3/nats-agents_0.1.3_linux_amd64.tar.gz"
      sha256 "fbd3f0f0a1dbfdab3f6089ab7c75579c8d5b479da98f12f62bd2fd81a2f7573d"
      define_method(:install) do
        bin.install "nats-agents"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/transactrx/nats-agent/releases/download/v0.1.3/nats-agents_0.1.3_linux_arm64.tar.gz"
      sha256 "54cc36fbd2ee6591f13ebce9e0d276e8a0f9af113afecc2222a66c88e510f86a"
      define_method(:install) do
        bin.install "nats-agents"
      end
    end
  end

  test do
    system "#{bin}/nats-agents", "--version"
  end
end
