# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NatsAgents < Formula
  desc "CLI to discover and drive NATS Agent Protocol agents and network tools"
  homepage "https://github.com/transactrx/nats-agent"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/transactrx/nats-agent/releases/download/v0.1.2/nats-agents_0.1.2_darwin_amd64.tar.gz"
      sha256 "21aef44e6753a77b80a3d4e49b16123ccce74f8a9e1eab68022fbc7730e769e2"

      define_method(:install) do
        bin.install "nats-agents"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/transactrx/nats-agent/releases/download/v0.1.2/nats-agents_0.1.2_darwin_arm64.tar.gz"
      sha256 "7f06d07f61473d747ab192f1b04247e5df5983663cba1b39ef8b712037dafadb"

      define_method(:install) do
        bin.install "nats-agents"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/transactrx/nats-agent/releases/download/v0.1.2/nats-agents_0.1.2_linux_amd64.tar.gz"
      sha256 "4a1b76e988b8b7061013a2869a0bbb81b7295bbb114e472018b2e6affbdb4647"
      define_method(:install) do
        bin.install "nats-agents"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/transactrx/nats-agent/releases/download/v0.1.2/nats-agents_0.1.2_linux_arm64.tar.gz"
      sha256 "52366b3acf52139bcbff5aead4af0cef5eae68ee93c8fa0150cfa19011b623b8"
      define_method(:install) do
        bin.install "nats-agents"
      end
    end
  end

  test do
    system "#{bin}/nats-agents", "--version"
  end
end
